version: '2'

services:
  dns:
    container_name: localdns
    build: .
    networks:
      brinternal:
        ipv4_address: 10.28.8.33
    restart: always
    hostname: casa
    domainname: blago.sexy

networks:
  brinternal:
    external: true
